#pragma once

#include <ntddk.h>
#include <wdf.h>

#define NTDEVICE_NAME      L"\\Device\\McuSmbusDrv"
#define SYMBOLIC_NAME      L"\\DosDevices\\McuSmbusDrv"

#define FILE_DEVICE_MCU_SMBUS  0x8000

#define IOCTL_MCU_PING     CTL_CODE(FILE_DEVICE_MCU_SMBUS, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MCU_ECHO_INC CTL_CODE(FILE_DEVICE_MCU_SMBUS, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _MCU_PING_OUT {
    UINT32 Value;
} MCU_PING_OUT, * PMCU_PING_OUT;

typedef struct _MCU_ECHO_INC_DATA
{
    ULONG Value;
} MCU_ECHO_INC_DATA, * PMCU_ECHO_INC_DATA;

EXTERN_C EVT_WDF_DRIVER_DEVICE_ADD McuSmbusDrvEvtDeviceAdd;
EXTERN_C EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL McuSmbusDrvEvtIoDeviceControl;