#pragma once

#include <ntddk.h>
#include <wdf.h>

#define NTDEVICE_NAME      L"\\Device\\McuSmbusDrv"
#define SYMBOLIC_NAME      L"\\DosDevices\\McuSmbusDrv"

#define FILE_DEVICE_MCU_SMBUS  0x8000

#define IOCTL_MCU_PING             CTL_CODE(FILE_DEVICE_MCU_SMBUS, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MCU_ECHO_INC         CTL_CODE(FILE_DEVICE_MCU_SMBUS, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MCU_GET_VERSION      CTL_CODE(FILE_DEVICE_MCU_SMBUS, 0x810, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MCU_GET_STATUS       CTL_CODE(FILE_DEVICE_MCU_SMBUS, 0x811, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MCU_SMBUS_READ       CTL_CODE(FILE_DEVICE_MCU_SMBUS, 0x812, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _MCU_PING_OUT {
    UINT32 Value;
} MCU_PING_OUT, * PMCU_PING_OUT;

typedef struct _MCU_ECHO_INC_DATA
{
    ULONG Value;
} MCU_ECHO_INC_DATA, * PMCU_ECHO_INC_DATA;

typedef struct _MCU_VERSION_OUT
{
    UINT16 Major;
    UINT16 Minor;
    UINT16 Patch;
    UINT16 Reserved;
} MCU_VERSION_OUT, * PMCU_VERSION_OUT;

typedef struct _MCU_STATUS_OUT
{
    UINT32 DriverReady;
    UINT32 McuConnected;
    UINT32 BusReady;
    UINT32 LastError;
} MCU_STATUS_OUT, * PMCU_STATUS_OUT;

#define MCU_SMBUS_MAX_DATA 256

typedef struct _MCU_SMBUS_READ_IN
{
    UINT8 BusId;
    UINT8 SlaveAddress;
    UINT8 Command;
    UINT8 ReadLength;
} MCU_SMBUS_READ_IN, * PMCU_SMBUS_READ_IN;

typedef struct _MCU_SMBUS_READ_OUT
{
    UINT32 BytesReturned;
    UINT8 Data[MCU_SMBUS_MAX_DATA];
} MCU_SMBUS_READ_OUT, * PMCU_SMBUS_READ_OUT;

EXTERN_C EVT_WDF_DRIVER_DEVICE_ADD McuSmbusDrvEvtDeviceAdd;
EXTERN_C EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL McuSmbusDrvEvtIoDeviceControl;